"""Add UserSkillHistory

Revision ID: 28d8f0142289
Revises: 94db0d44bb26
Create Date: 2026-08-12 20:00:26.815784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28d8f0142289'
down_revision: Union[str, Sequence[str], None] = '94db0d44bb26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_skill_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('previous_state', sa.String(), nullable=True),
    sa.Column('new_state', sa.String(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['repository_snapshots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_skill_history_id'), 'user_skill_history', ['id'], unique=False)
    op.create_index(op.f('ix_user_skill_history_skill_id'), 'user_skill_history', ['skill_id'], unique=False)
    op.create_index(op.f('ix_user_skill_history_snapshot_id'), 'user_skill_history', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_user_skill_history_user_id'), 'user_skill_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_skill_history_user_id'), table_name='user_skill_history')
    op.drop_index(op.f('ix_user_skill_history_snapshot_id'), table_name='user_skill_history')
    op.drop_index(op.f('ix_user_skill_history_skill_id'), table_name='user_skill_history')
    op.drop_index(op.f('ix_user_skill_history_id'), table_name='user_skill_history')
    op.drop_table('user_skill_history')
    # ### end Alembic commands ###
