"""phase2_github_evidence

Revision ID: 83170069488a
Revises: 001_initial
Create Date: 2026-08-10 12:22:52.335533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83170069488a'
down_revision: Union[str, Sequence[str], None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('github_repo_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_github_repo_id'), 'projects', ['github_repo_id'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('repository_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('commit_sha', sa.String(), nullable=True),
    sa.Column('branch', sa.String(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('analysis_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('analysis_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ANALYZING', 'COMPLETED', 'FAILED', name='snapshotstatus', native_enum=False, length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repository_snapshots_id'), 'repository_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_repository_snapshots_project_id'), 'repository_snapshots', ['project_id'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['repository_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_file_path'), 'artifacts', ['file_path'], unique=False)
    op.create_index(op.f('ix_artifacts_id'), 'artifacts', ['id'], unique=False)
    op.create_index(op.f('ix_artifacts_snapshot_id'), 'artifacts', ['snapshot_id'], unique=False)
    op.create_table('raw_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artifact_id', sa.Integer(), nullable=False),
    sa.Column('observation_text', sa.String(), nullable=False),
    sa.Column('line_numbers', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_observations_artifact_id'), 'raw_observations', ['artifact_id'], unique=False)
    op.create_index(op.f('ix_raw_observations_id'), 'raw_observations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_observations_id'), table_name='raw_observations')
    op.drop_index(op.f('ix_raw_observations_artifact_id'), table_name='raw_observations')
    op.drop_table('raw_observations')
    op.drop_index(op.f('ix_artifacts_snapshot_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_file_path'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_repository_snapshots_project_id'), table_name='repository_snapshots')
    op.drop_index(op.f('ix_repository_snapshots_id'), table_name='repository_snapshots')
    op.drop_table('repository_snapshots')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_github_repo_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
