"""Phase 3 Evidence Engine

Revision ID: 87d1adc23847
Revises: 83170069488a
Create Date: 2026-08-10 12:55:29.600183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87d1adc23847'
down_revision: Union[str, Sequence[str], None] = '83170069488a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_observation_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('IMPLEMENTATION', 'TESTING', 'CONFIGURATION', 'CI_CD', 'DATABASE', 'AUTHENTICATION', 'API', 'ARCHITECTURE', 'DOCUMENTATION', 'CONTAINERIZATION', 'DEPENDENCY', 'OBSERVABILITY', name='evidencetype', native_enum=False, length=50), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('freshness_weight', sa.Float(), nullable=False),
    sa.Column('source_reference', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['raw_observation_id'], ['raw_observations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_id'), 'evidence', ['id'], unique=False)
    op.create_index(op.f('ix_evidence_raw_observation_id'), 'evidence', ['raw_observation_id'], unique=False)
    op.create_table('evidence_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evidence_id', 'skill_id', name='uq_evidence_skill')
    )
    op.create_index(op.f('ix_evidence_skills_evidence_id'), 'evidence_skills', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_evidence_skills_id'), 'evidence_skills', ['id'], unique=False)
    op.create_index(op.f('ix_evidence_skills_skill_id'), 'evidence_skills', ['skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_skills_skill_id'), table_name='evidence_skills')
    op.drop_index(op.f('ix_evidence_skills_id'), table_name='evidence_skills')
    op.drop_index(op.f('ix_evidence_skills_evidence_id'), table_name='evidence_skills')
    op.drop_table('evidence_skills')
    op.drop_index(op.f('ix_evidence_raw_observation_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_id'), table_name='evidence')
    op.drop_table('evidence')
    # ### end Alembic commands ###
