"""Add Gap model

Revision ID: 8f42a0323c91
Revises: f404277542d9
Create Date: 2026-08-10 19:12:37.353927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f42a0323c91'
down_revision: Union[str, Sequence[str], None] = 'f404277542d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('actual_state', sa.String(), nullable=False),
    sa.Column('required_state', sa.String(), nullable=False),
    sa.Column('state_distance', sa.Integer(), nullable=False),
    sa.Column('importance_weight', sa.Float(), nullable=False),
    sa.Column('severity', sa.Float(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('calculation_version', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'skill_id', name='uq_user_gap')
    )
    op.create_index(op.f('ix_gaps_id'), 'gaps', ['id'], unique=False)
    op.create_index(op.f('ix_gaps_skill_id'), 'gaps', ['skill_id'], unique=False)
    op.create_index(op.f('ix_gaps_user_id'), 'gaps', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gaps_user_id'), table_name='gaps')
    op.drop_index(op.f('ix_gaps_skill_id'), table_name='gaps')
    op.drop_index(op.f('ix_gaps_id'), table_name='gaps')
    op.drop_table('gaps')
    # ### end Alembic commands ###
