"""Add settings preferences to StudentProfile

Revision ID: 94db0d44bb26
Revises: 0f27607d3996
Create Date: 2026-08-12 19:41:11.002305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94db0d44bb26'
down_revision: Union[str, Sequence[str], None] = '0f27607d3996'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('notify_weekly_report', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('student_profiles', sa.Column('notify_gap_alerts', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('student_profiles', sa.Column('public_profile', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('student_profiles', sa.Column('show_raw_github_stats', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_profiles', 'show_raw_github_stats')
    op.drop_column('student_profiles', 'public_profile')
    op.drop_column('student_profiles', 'notify_gap_alerts')
    op.drop_column('student_profiles', 'notify_weekly_report')
    # ### end Alembic commands ###
