"""phase_14_telemetry

Revision ID: d7ae63f95115
Revises: fd2e5e7a62c6
Create Date: 2026-08-16 21:29:31.794904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7ae63f95115'
down_revision: Union[str, Sequence[str], None] = 'fd2e5e7a62c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_events_created_at'), 'product_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_product_events_event_type'), 'product_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_product_events_id'), 'product_events', ['id'], unique=False)
    op.create_index(op.f('ix_product_events_user_id'), 'product_events', ['user_id'], unique=False)
    op.create_table('product_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('feature_context', sa.String(length=100), nullable=False),
    sa.Column('is_helpful', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_feedback_feature_context'), 'product_feedback', ['feature_context'], unique=False)
    op.create_index(op.f('ix_product_feedback_id'), 'product_feedback', ['id'], unique=False)
    op.create_index(op.f('ix_product_feedback_user_id'), 'product_feedback', ['user_id'], unique=False)
    op.add_column('users', sa.Column('is_internal', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_internal')
    op.drop_index(op.f('ix_product_feedback_user_id'), table_name='product_feedback')
    op.drop_index(op.f('ix_product_feedback_id'), table_name='product_feedback')
    op.drop_index(op.f('ix_product_feedback_feature_context'), table_name='product_feedback')
    op.drop_table('product_feedback')
    op.drop_index(op.f('ix_product_events_user_id'), table_name='product_events')
    op.drop_index(op.f('ix_product_events_id'), table_name='product_events')
    op.drop_index(op.f('ix_product_events_event_type'), table_name='product_events')
    op.drop_index(op.f('ix_product_events_created_at'), table_name='product_events')
    op.drop_table('product_events')
    # ### end Alembic commands ###
