"""Add missing phase 13 models

Revision ID: fd2e5e7a62c6
Revises: ccc110188a63
Create Date: 2026-08-15 13:05:41.829873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd2e5e7a62c6'
down_revision: Union[str, Sequence[str], None] = 'ccc110188a63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cohorts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('educator_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('course_code', sa.String(), nullable=False),
    sa.Column('invite_code', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['educator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cohorts_educator_id'), 'cohorts', ['educator_id'], unique=False)
    op.create_index(op.f('ix_cohorts_id'), 'cohorts', ['id'], unique=False)
    op.create_index(op.f('ix_cohorts_invite_code'), 'cohorts', ['invite_code'], unique=True)
    op.create_table('mentor_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=True),
    sa.Column('invite_token', sa.String(), nullable=False),
    sa.Column('mentor_email', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REVOKED', 'EXPIRED', name='relationshipstatus', native_enum=False, length=20), nullable=False),
    sa.Column('permissions', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mentor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentor_relationships_id'), 'mentor_relationships', ['id'], unique=False)
    op.create_index(op.f('ix_mentor_relationships_invite_token'), 'mentor_relationships', ['invite_token'], unique=True)
    op.create_index(op.f('ix_mentor_relationships_mentor_id'), 'mentor_relationships', ['mentor_id'], unique=False)
    op.create_index(op.f('ix_mentor_relationships_student_id'), 'mentor_relationships', ['student_id'], unique=False)
    op.create_table('sharing_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_owner_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resource_owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sharing_audit_logs_actor_id'), 'sharing_audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_sharing_audit_logs_id'), 'sharing_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_sharing_audit_logs_resource_owner_id'), 'sharing_audit_logs', ['resource_owner_id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('invite_code', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_creator_id'), 'teams', ['creator_id'], unique=False)
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_index(op.f('ix_teams_invite_code'), 'teams', ['invite_code'], unique=True)
    op.create_table('user_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('claim_text', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_claims_id'), 'user_claims', ['id'], unique=False)
    op.create_index(op.f('ix_user_claims_user_id'), 'user_claims', ['user_id'], unique=False)
    op.create_table('cohort_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cohort_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cohort_memberships_cohort_id'), 'cohort_memberships', ['cohort_id'], unique=False)
    op.create_index(op.f('ix_cohort_memberships_id'), 'cohort_memberships', ['id'], unique=False)
    op.create_index(op.f('ix_cohort_memberships_student_id'), 'cohort_memberships', ['student_id'], unique=False)
    op.create_table('mentor_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relationship_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('note_text', sa.Text(), nullable=False),
    sa.Column('recommended_quest_id', sa.Integer(), nullable=True),
    sa.Column('recommended_concept_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['relationship_id'], ['mentor_relationships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentor_notes_author_id'), 'mentor_notes', ['author_id'], unique=False)
    op.create_index(op.f('ix_mentor_notes_id'), 'mentor_notes', ['id'], unique=False)
    op.create_index(op.f('ix_mentor_notes_relationship_id'), 'mentor_notes', ['relationship_id'], unique=False)
    op.create_index(op.f('ix_mentor_notes_student_id'), 'mentor_notes', ['student_id'], unique=False)
    op.create_table('review_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_links_id'), 'review_links', ['id'], unique=False)
    op.create_index(op.f('ix_review_links_project_id'), 'review_links', ['project_id'], unique=False)
    op.create_index(op.f('ix_review_links_student_id'), 'review_links', ['student_id'], unique=False)
    op.create_index(op.f('ix_review_links_token'), 'review_links', ['token'], unique=True)
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_members_id'), 'team_members', ['id'], unique=False)
    op.create_index(op.f('ix_team_members_team_id'), 'team_members', ['team_id'], unique=False)
    op.create_index(op.f('ix_team_members_user_id'), 'team_members', ['user_id'], unique=False)
    op.create_table('team_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('shared_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_projects_id'), 'team_projects', ['id'], unique=False)
    op.create_index(op.f('ix_team_projects_project_id'), 'team_projects', ['project_id'], unique=False)
    op.create_index(op.f('ix_team_projects_team_id'), 'team_projects', ['team_id'], unique=False)
    op.add_column('projects', sa.Column('is_public', sa.Boolean(), nullable=False))
    op.create_unique_constraint('uq_user_github_repo', 'projects', ['user_id', 'github_repo_id'])
    op.add_column('student_profiles', sa.Column('nexus_id', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('public_slug', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('bio', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('external_links', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('show_journey', sa.Boolean(), nullable=False))
    op.add_column('student_profiles', sa.Column('show_proof', sa.Boolean(), nullable=False))
    op.add_column('student_profiles', sa.Column('show_unexplored', sa.Boolean(), nullable=False))
    op.add_column('student_profiles', sa.Column('show_email', sa.Boolean(), nullable=False))
    op.add_column('student_profiles', sa.Column('featured_project_ids', sa.String(), nullable=True))
    op.create_index(op.f('ix_student_profiles_nexus_id'), 'student_profiles', ['nexus_id'], unique=True)
    op.create_index(op.f('ix_student_profiles_public_slug'), 'student_profiles', ['public_slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_profiles_public_slug'), table_name='student_profiles')
    op.drop_index(op.f('ix_student_profiles_nexus_id'), table_name='student_profiles')
    op.drop_column('student_profiles', 'featured_project_ids')
    op.drop_column('student_profiles', 'show_email')
    op.drop_column('student_profiles', 'show_unexplored')
    op.drop_column('student_profiles', 'show_proof')
    op.drop_column('student_profiles', 'show_journey')
    op.drop_column('student_profiles', 'external_links')
    op.drop_column('student_profiles', 'bio')
    op.drop_column('student_profiles', 'public_slug')
    op.drop_column('student_profiles', 'nexus_id')
    op.drop_constraint('uq_user_github_repo', 'projects', type_='unique')
    op.drop_column('projects', 'is_public')
    op.drop_index(op.f('ix_team_projects_team_id'), table_name='team_projects')
    op.drop_index(op.f('ix_team_projects_project_id'), table_name='team_projects')
    op.drop_index(op.f('ix_team_projects_id'), table_name='team_projects')
    op.drop_table('team_projects')
    op.drop_index(op.f('ix_team_members_user_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_team_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_id'), table_name='team_members')
    op.drop_table('team_members')
    op.drop_index(op.f('ix_review_links_token'), table_name='review_links')
    op.drop_index(op.f('ix_review_links_student_id'), table_name='review_links')
    op.drop_index(op.f('ix_review_links_project_id'), table_name='review_links')
    op.drop_index(op.f('ix_review_links_id'), table_name='review_links')
    op.drop_table('review_links')
    op.drop_index(op.f('ix_mentor_notes_student_id'), table_name='mentor_notes')
    op.drop_index(op.f('ix_mentor_notes_relationship_id'), table_name='mentor_notes')
    op.drop_index(op.f('ix_mentor_notes_id'), table_name='mentor_notes')
    op.drop_index(op.f('ix_mentor_notes_author_id'), table_name='mentor_notes')
    op.drop_table('mentor_notes')
    op.drop_index(op.f('ix_cohort_memberships_student_id'), table_name='cohort_memberships')
    op.drop_index(op.f('ix_cohort_memberships_id'), table_name='cohort_memberships')
    op.drop_index(op.f('ix_cohort_memberships_cohort_id'), table_name='cohort_memberships')
    op.drop_table('cohort_memberships')
    op.drop_index(op.f('ix_user_claims_user_id'), table_name='user_claims')
    op.drop_index(op.f('ix_user_claims_id'), table_name='user_claims')
    op.drop_table('user_claims')
    op.drop_index(op.f('ix_teams_invite_code'), table_name='teams')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_creator_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_sharing_audit_logs_resource_owner_id'), table_name='sharing_audit_logs')
    op.drop_index(op.f('ix_sharing_audit_logs_id'), table_name='sharing_audit_logs')
    op.drop_index(op.f('ix_sharing_audit_logs_actor_id'), table_name='sharing_audit_logs')
    op.drop_table('sharing_audit_logs')
    op.drop_index(op.f('ix_mentor_relationships_student_id'), table_name='mentor_relationships')
    op.drop_index(op.f('ix_mentor_relationships_mentor_id'), table_name='mentor_relationships')
    op.drop_index(op.f('ix_mentor_relationships_invite_token'), table_name='mentor_relationships')
    op.drop_index(op.f('ix_mentor_relationships_id'), table_name='mentor_relationships')
    op.drop_table('mentor_relationships')
    op.drop_index(op.f('ix_cohorts_invite_code'), table_name='cohorts')
    op.drop_index(op.f('ix_cohorts_id'), table_name='cohorts')
    op.drop_index(op.f('ix_cohorts_educator_id'), table_name='cohorts')
    op.drop_table('cohorts')
    # ### end Alembic commands ###
