"""add vector embeddings

Revision ID: 0a539df45cd1
Revises: 507bf125be1d
Create Date: 2026-10-02 09:49:23.897666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.vector_type


# revision identifiers, used by Alembic.
revision: str = '0a539df45cd1'
down_revision: Union[str, None] = '507bf125be1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('embedding', app.models.vector_type.HybridVector(dim=768), nullable=True))
    op.add_column('document_chunks', sa.Column('embedding_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'embedding_metadata')
    op.drop_column('document_chunks', 'embedding')
    # ### end Alembic commands ###
