"""Add evidence models and update action status

Revision ID: d3e303dce522
Revises: 0a539df45cd1
Create Date: 2026-10-02 18:57:20.139542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3e303dce522'
down_revision: Union[str, None] = '0a539df45cd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_requirements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('action_id', sa.Uuid(), nullable=False),
    sa.Column('tool_id', sa.String(length=128), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('expected_state', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_requirements_action_id'), 'evidence_requirements', ['action_id'], unique=False)
    op.create_index(op.f('ix_evidence_requirements_tenant_id'), 'evidence_requirements', ['tenant_id'], unique=False)
    op.create_table('executions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('action_id', sa.Uuid(), nullable=False),
    sa.Column('requester_id', sa.Uuid(), nullable=True),
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('capability', sa.String(length=64), nullable=False),
    sa.Column('tool_id', sa.String(length=128), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('policy_decision', sa.String(length=32), nullable=True),
    sa.Column('approval_decision', sa.String(length=32), nullable=True),
    sa.Column('approver_id', sa.Uuid(), nullable=True),
    sa.Column('approval_reason', sa.String(), nullable=True),
    sa.Column('result_payload', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executions_action_id'), 'executions', ['action_id'], unique=False)
    op.create_index(op.f('ix_executions_capability'), 'executions', ['capability'], unique=False)
    op.create_index(op.f('ix_executions_requester_id'), 'executions', ['requester_id'], unique=False)
    op.create_index(op.f('ix_executions_state'), 'executions', ['state'], unique=False)
    op.create_index(op.f('ix_executions_tenant_id'), 'executions', ['tenant_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('requirement_id', sa.Uuid(), nullable=False),
    sa.Column('execution_record_id', sa.Uuid(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_record_id'], ['executions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requirement_id'], ['evidence_requirements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_execution_record_id'), 'evidence', ['execution_record_id'], unique=False)
    op.create_index(op.f('ix_evidence_requirement_id'), 'evidence', ['requirement_id'], unique=False)
    op.create_index(op.f('ix_evidence_tenant_id'), 'evidence', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_tenant_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_requirement_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_execution_record_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_executions_tenant_id'), table_name='executions')
    op.drop_index(op.f('ix_executions_state'), table_name='executions')
    op.drop_index(op.f('ix_executions_requester_id'), table_name='executions')
    op.drop_index(op.f('ix_executions_capability'), table_name='executions')
    op.drop_index(op.f('ix_executions_action_id'), table_name='executions')
    op.drop_table('executions')
    op.drop_index(op.f('ix_evidence_requirements_tenant_id'), table_name='evidence_requirements')
    op.drop_index(op.f('ix_evidence_requirements_action_id'), table_name='evidence_requirements')
    op.drop_table('evidence_requirements')
    # ### end Alembic commands ###
